### ISSUE TITLE
Implement text search with Postgres

### ISSUE THREAD

**Issue by Kamo533** [cdp-group4/exportcontrol#39]
- [x] Test paragraph search on law data
- [x] Research what we should use for search result ranking
- [x] Show search results according to their rank
- [x] Categorize your results in terms of how the export control law affects you

**Comment by KatjaSi** [comment]
- [x] Add categories/ subcategories / regimes in the dropdown menu
- [x] Research how we should index fields for faster search
- [x] Paginate search results
- [x] Implement search filters on categories, subcategories, regimes
