### ISSUE TITLE
Frontend: Add categories/ subcategories in the dropdown menu

### ISSUE THREAD

**Issue by Kamo533** [cdp-group4/exportcontrol#42]

**Comment by Kamo533** [comment]
Perhaps use an own file that are defining category, subcategory and regime.
Or we can ask the DB for the types of categories when loading the page

**Comment by KatjaSi** [comment]
these can be easily fetched from the database (is done in branch  add-search-child), this is related to issue #39 I suppose. So it could be a subtask in #39.
